### ISSUE TITLE
Feature: Ability to reupload project

### ISSUE THREAD

**Issue by Prab-N** [SDS-Program-Pool/pooler#68]
If you notice an issue with your upload you should be able to remove/reupload the code before it is reviewed.

**Comment by ctaylor-c172** [comment]
Thank you!

To do:

- Implement project soft deletion by user and log within system.

**Comment by ctaylor-c172** [comment]
This feature will not be implemented at this moment in time. Project deletion will be supported instead, allowing creation and deletion. There are too many things to think about by having modify project such as timing lock, locking modification once someone has clicked download and hence tracking downloads etc. Would be a nicer workflow. But too much hassle for now.
