### ISSUE TITLE
Feedback character limit

### ISSUE THREAD

**Issue by cowsay652** [SDS-Program-Pool/pooler#70]
**Bug:**
When submitting feedback greater than 500 characters, an error message appears that states that the field shouldn't be greater than 500 characters, even though the UI states that the character limit is 4000.
![image](https://user-images.githubusercontent.com/33980939/148764994-fbf4523b-8a5b-467a-abc7-a83f68e912e3.png)

**Comment by ctaylor-c172** [comment]
Thank you.
Will be fixed.

To Do:
- Server side validation rule must be changed to 4000 chars
- Validation error message must be modified to match gov.uk frontend

**Comment by ctaylor-c172** [comment]
@cowsay652 - Fixed, to be deployed on version 1.1. Ty
