### ISSUE TITLE
500 server error when uploading new project

### ISSUE THREAD

**Issue by Prab-N** [SDS-Program-Pool/pooler#75]
After uploading a new .zip and clicking 'Save and Continue', I receive '500 | Server Error'

**Comment by Prab-N** [comment]
Update: The error is resolved but now my program has been uploaded 12 times

**Comment by ctaylor-c172** [comment]
@Prab-N Thank you for reporting this!

This issue will be closed as it is not directly to do with the open source project but the current deployment within our organisation.
